# Generated by Django 5.0.6 on 2024-06-10 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeatAllotment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.CharField(max_length=255)),
                ('academic_program_name', models.CharField(max_length=255)),
                ('seat_type', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255, null=True)),
                ('opening_rank', models.IntegerField()),
                ('closing_rank', models.IntegerField()),
                ('year', models.IntegerField()),
                ('rounds', models.IntegerField()),
            ],
        ),
    ]
