# Generated by Django 5.0.6 on 2024-06-12 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seatallotment',
            old_name='academic_program_name',
            new_name='academic_program',
        ),
    ]
